---
galaxy_info:
  author: Mad-Axell
  description: Ansible role for deploying and configuring Portainer - a web interface for managing Docker containers
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - portainer
    - docker
    - container
    - management
    - web-interface
    - gui
    - orchestration

dependencies:
  - name: docker
    version: ">=1.0.0"

