---
# Portainer version
version: latest

# Role settings
remove_persistent_data: false
remove_existing_container: false
persistent_data_path: /opt/portainer:/data
container_image: portainer/portainer:{{ version }}
container_name: portainer 
container_labels: {}
container_network:
container_restart_policy: always
container_recreate: false
container_privileged: true  # Boolean. Run container in privileged mode / Логическое значение. Запускать контейнер в привилегированном режиме

# Networking
host_port: 9000
container_ports:
  - "9000:9000"