---
galaxy_info:
  author: "Ansible Automation"
  description: "Role for mounting SMB/CIFS shares on Proxmox host and binding them to LXC containers"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - proxmox
    - lxc
    - samba
    - cifs
    - mount
    - storage

dependencies: []

